apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: internal
  name: internal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal
  strategy: {}
  template:
    metadata:
      labels:
        app: internal
    spec:
      containers:
      - image: gcr.io/twitterfeedstokafkatest/devoops_internal:v1.0
        name: internal
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "256Mi"
            cpu: "0.2"
status: {}
